export default {
  color: '#f07c3a',
  background: 'whitesmoke',
  buttonsStyling: false,
  reverseButtons: true,
  showCloseButton: true,
  customClass: {
    container: 'sw__container',
    popup: 'sw__popup',
    header: 'sw__header',
    title: 'sw__title',
    closeButton: '.sw__close-button',
    icon: 'sw__icon',
    image: 'sw__image',
    htmlContainer: 'sw__html-container',
    input: 'sw__input',
    inputLabel: 'sw__input-label',
    validationMessage: 'sw__validation-message',
    actions: 'sw__actions',
    confirmButton: 'sw__confirm-button',
    denyButton: 'sw__deny-button',
    cancelButton: 'sw__cancel-button',
    loader: 'sw__loader',
    footer: 'sw__footer',
    timerProgressBar: 'sw__timer-progress-bar',
  },
}
